# SDLC 4.7 Compliance Configuration
# HR Profiling & Assessment Platform
# Version: 4.7.0
# Date: October 11, 2025
# Status: ACTIVE DEPLOYMENT

## Project Information
PROJECT_NAME: "HR Profiling & Assessment Platform"
PROJECT_TYPE: "Full-Stack Web Application"
TEAM_SIZE: "5-10 developers + AI agents"
AI_TOOLS: ["GitHub Copilot", "Claude Code", "Cursor IDE"]

## Five Pillar Implementation

### Pillar 1: AI-Native Excellence Standards
ZERO_MOCK_POLICY: true
DESIGN_FIRST: true
QUALITY_GATE_THRESHOLD: 95
AI_COMPATIBLE_WORKFLOWS: true

### Pillar 2: AI+Human Orchestration
AI_ROLES_ENABLED: true
INTERCHANGEABLE_ROLES: true
DAILY_STANDUP_WITH_AI: true
AI_AS_TEAM_MEMBER: true

### Pillar 3: Quality Governance System
SEVERITY_CLASSIFICATION:
  CRITICAL: "Immediate fix (mocks, API breaks)"
  HIGH: "24-hour fix (performance, coverage)"
  MEDIUM: "Sprint fix (style, naming)"
  LOW: "Next sprint (optimizations)"

CRISIS_RESPONSE_TIME:
  DETECTION: "5 minutes"
  ASSESSMENT: "1 hour"
  RESOLUTION: "48 hours"

### Pillar 4: Documentation Permanence
PERMANENT_NAMING: true
NO_SPRINT_REFERENCES: true
NO_VERSION_IN_FILENAMES: true
AI_PARSEABLE_FORMATS: true

### Pillar 5: Continuous Compliance
REAL_TIME_MONITORING: true
PRE_COMMIT_HOOKS: true
AUTOMATED_ALERTS: true
EXECUTIVE_DASHBOARD: true

## Team Roles (AI+Human)

### Core Team
- CTO: Strategic leadership and architecture
- CPO: Product management and user experience
- Lead Developer: Technical implementation
- QA Engineer: Quality assurance and testing
- DevOps Engineer: Operations and deployment

### AI Agents
- GitHub Copilot: Code generation and review
- Claude Code Developer: Full-stack development
- Claude Code Architect: System design
- Claude Code QA: Testing and validation
- Claude Code DevOps: Operations automation

## Compliance Metrics
TARGET_COMPLIANCE_SCORE: 95
MOCK_TOLERANCE: 0
DOCUMENTATION_COVERAGE: 100
TEST_COVERAGE: 85
PERFORMANCE_THRESHOLD: "<50ms API response"

## Implementation Timeline
WEEK_1: "Foundation & Assessment"
WEEK_2: "Documentation Standards"
WEEK_3: "Pre-commit Hooks Setup"
WEEK_4: "AI Role Templates"
WEEK_5: "Quality Governance"
WEEK_6: "Continuous Monitoring"